apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DATABASE_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvYm9va19tYW5hZ2Vy"
  POSTGRES_USER: "cG9zdGdyZXM="
  POSTGRES_DB: "Ym9va19tYW5hZ2Vy"
  POSTGRES_PASSWORD: "cG9zdGdyZXM="
  POSTGRES_HOST: "cG9zdGdyZXM="
  NODE_ENV: "ZGV2ZWxvcG1lbnQ="
  API_URL: "aHR0cDovL2JhY2tlbmQtc2VydmljZTo4MDAw"
  BACKEND_PORT: "ODAwMA=="
